# Generated by Django 3.1.12 on 2025-10-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20251013_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='emotion_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
