# Generated by Django 3.1.12 on 2025-10-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20251018_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.5)),
                ('recommendations', models.JSONField()),
                ('encouragement', models.TextField()),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(default='fas fa-lightbulb', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='journal.note')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
