# Generated by Django 3.1.12 on 2025-10-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_activityrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecommendation',
            name='enriched_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityrecommendation',
            name='enrichment_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityrecommendation',
            name='has_enrichment',
            field=models.BooleanField(default=False),
        ),
    ]
