# Generated by Django 4.1.13 on 2025-10-23 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_gallery_models'),
        ('journal', '0007_auto_20251021_0238'),
    ]

    operations = [
    ]
