# Generated by Django 3.2.25 on 2025-10-26 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0008_merge_0002_gallery_models_0007_auto_20251021_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('tone', models.CharField(
                    choices=[
                        ('calm', 'Calm'),
                        ('motivational', 'Motivational'),
                        ('self_compassion', 'Self-Compassion'),
                        ('focus', 'Focus'),
                        ('confidence', 'Confidence')
                    ],
                    default='calm',
                    max_length=32
                )),
                ('topic', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user_affirmations',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
