# Generated by Django 3.2.20 on 2025-10-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_populate_unique_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='📁', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
