# Generated by Django 3.2.25 on 2025-10-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20251025_1301'),
        ('journal', '0009_auto_20251026_0132'),
    ]

    operations = [
    ]
